// <auto-generated />
using AnimalKingDomWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalKingDomWebApi.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20190930120906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnimalKingDomWebApi.Models.AnimalDetails", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diet");

                    b.Property<string>("Lifespan");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Population");

                    b.Property<string>("UrlImage");

                    b.HasKey("AnimalId");

                    b.ToTable("AnimalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
